"""create scores and duels tables

Revision ID: 0897347047fa
Revises: 
Create Date: 2026-04-06 22:46:58.571728

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '0897347047fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duels',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('player_a', sa.String(length=32), nullable=False),
    sa.Column('player_b', sa.String(length=32), nullable=True),
    sa.Column('score_a', sa.Integer(), nullable=True),
    sa.Column('score_b', sa.Integer(), nullable=True),
    sa.Column('winner', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player', sa.String(length=32), nullable=False),
    sa.Column('reaction_ms', sa.Integer(), nullable=False),
    sa.Column('duel_id', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['duel_id'], ['duels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_duel_id'), 'scores', ['duel_id'], unique=False)
    op.create_index(op.f('ix_scores_id'), 'scores', ['id'], unique=False)
    op.create_index(op.f('ix_scores_player'), 'scores', ['player'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scores_player'), table_name='scores')
    op.drop_index(op.f('ix_scores_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_duel_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_table('duels')
    # ### end Alembic commands ###
